### ISSUE TITLE
Building Gadget aborts structure placement on reaching items without EMC.

### ISSUE THREAD

**Issue by James103** [Team-Fruit/EMCGadgets#1]
When I attempt to copy-paste a structure that contains items that don't have EMC, then the structure placement aborts even if I have enough EMC to complete the rest of the build, I have all of the transmutation knowledge possible, and I have the non-EMC items available in my inventory. The structure placement aborts because of a division by zero in the routine that places the structure.

Workaround: Place the non-EMC items manually or add EMC to them.

Possible Solution: Warn in a better way about blocks that don't have EMC when building a structure that contains such blocks (such as by highlighting such blocks in red and/or listing them out)

Last four crash logs:
https://paste.dimdev.org/famawuvoci.mccrash
https://paste.dimdev.org/gusuyeguqe.mccrash
https://paste.dimdev.org/iqezitorop.mccrash (this actually resulted in a crash)
https://paste.dimdev.org/udesibagen.mccrash

Modpack being used:
![image](https://user-images.githubusercontent.com/37945304/77132600-2f21b700-6a2e-11ea-9cf8-c741ff031a11.png)

EDIT: The game just crashed again:
https://paste.dimdev.org/vayixaqesu.mccrash

**Comment by Speecker** [comment]
Hey :) I get the same Crash and Error Report whenever i try to build with Blocks that dont have any EMC value, even if i have some of them in my inventory. Would be nice to make the mod recognize non-EMC Blocks and able to handle them so the game wont crash but instead just dont try to calculate EMC cost for these blocks and behave like the BuildingGadgets without EMC Gadgets active.

**Comment by James103** [comment]
Closing, as the mod appears to no longer be maintained and `paste.dimdev.org` is not what it once was.
